### PR TITLE
Use loop variable instead of 0

### PR DESCRIPTION
**Pull request by DamirAinullin**
i instead of 0.

### CODE REVIEW

**Comment by NickCraver** [comment]
Oh interesting - do you have an example test where this was failing before that we can add to prevent regression?

**Comment by DamirAinullin** [comment]
Changed exisiting unit test if you don't mind. Added one more level. Without the fix this test will be failed.

**Comment by DamirAinullin** [comment]
Is it OK?

**Comment by mgravell** [comment]
merging, thanks

**Pull request merged**
