### PR TITLE
make CreateParamInfoGenerator and GetTypeDeserializerImpl can be cust…

### PR DESCRIPTION
**Pull request by fredliex**
hi, I need to custom emit for special rule,
so modify some code to allow SqlMapper's CreateParamInfoGenerator and GetTypeDeserializerImpl can be customized.

hope can commit this request, thanks a lot,

### CODE REVIEW

**Comment by NickCraver** [comment]
@mgravell Thoughts here? I'm *very* hesitant on making any API like this public. I think the very narrow use case vs. the brittleness it introduces likely isn't worth the tradeoff.

**Comment by NickCraver** [comment]
@fredliex Can you please explain your use case here?

**Comment by fredliex** [comment]
@NickCraver 
in my case, need more control for object to param and DataReader to typed model.
I use attribute to define behavior, ex:
1. auto TrimEnd char to string property.
2. null member property <--> not null columen
3. Enum <--> special string
4. property name a  <---> column name b
5. mapping nonpublic property/field
6. etc...

example in 
https://github.com/fredliex/Framework.Dapper/blob/master/Framwork.Dapper/Framework.Dapper.Test/DataTest.cs

sorry for the comment is chinese language.

**Comment by NickCraver** [comment]
@fredliex I think the blunt answer here is: I don't think this belongs in the core lib. It'd be very brittle and greatly restrict us in refactoring the inner bits. I think if you're going *that* far custom, a fork is in order.

**Pull request closed without merging**
