### PR TITLE
Add support for Oracle to Dapper.Contrib

### PR DESCRIPTION
**Pull request by Minx-SigEp**
-- Added support for Sequences
-- Modified the ISqlAdapter interface
    -- Added property SequenceSupported
    -- Added methods AppendParameter and AppendSequenceNextValue
-- Update the SQL generation code to use the new methods added to ISqlAdapeter

### CODE REVIEW

**Comment by NickCraver** [comment]
This seems to be several PRs combined into one - trying to address much more than just Oracle support (e.g. parameter fixing etc.) The main issue I see is `ISqlAdapter` changes, which is a breaking change we must reserve for the next major release. The other is: we'll need a test suite for this as well (you can see how to add based on the other abstract implementations).

I'm not against the approach, but it needs more of a look - just wanted to give some quick feedback on items.

**Comment by Minx-SigEp** [comment]
Nick. Thanks for the quick response. 

I figured I would get called out about the missing tests, I will work on them tonight if I get a chance. I agree with you that changing `ISqlAdapter ` is a breaking change, but are you not currently in beta or have you moved to RC already. If in beta I would think this would be a great time to get these changes include. Let me know your thoughts 

Thanks again 
Matt

**Comment by Minx-SigEp** [comment]
TestSuite is a work in progress. Will finish it later this week.

**Comment by mgravell** [comment]
Also:
C:\projects\dapper-dot-net-27k3h\Dapper.Tests.Contrib\TestSuites.cs(7,7): DNXCore,Version=v5.0 error CS0246: The type or namespace name 'Oracle' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\dapper-dot-net-27k3h\Dapper.Tests.Contrib\Dapper.Tests.Contrib.xproj]
      0 Warning(s)
      2 Error(s)
  Time elapsed 00:00:11.2906109
  Total build time elapsed: 00:00:11.2974283
  Total projects built: 1
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.Targets(158,5): error : Build failed. [C:\projects\dapper-dot-net-27k3h\Dapper.Tests.Contrib\Dapper.Tests.Contrib.xproj]
Command exited with code 1

**Comment by dipdapdop** [comment]
@NickCraver Apologies for commenting on an old PR.  This announcement from Oracle may be of interest: https://twitter.com/OracleDOTNET/status/841310384850067457 (Roadmap announcement for Oracle Managed Data Access Provider support in .Net Core 2.0).  Expected end of 2017 - too late for inclusion in v2.0 of `Dapper.Contrib` I guess.

**Comment by Minx-SigEp** [comment]
I have not had time to work on this as hopped and it has sat and rotted. Because I have no plans of being able to work on this anytime soon I am going to close this PR.

**Pull request closed without merging**
